import moment from 'moment';

const USER_LOGGED_IN = 'User logged in successfully';
const USER_CREATED = 'User created successfully';

const VERIFICATION_CODE_SENT = 'Verification code sent to your email';
const VERIFICATION_CODE_EMAIL_SUBJECT = 'Verification code: ';
const VERIFICATION_CODE_EMAIL_TEXT = 'Verification code text';
const VERIFICATION_CODE_GENERATE_LIMIT = 5;
const VERIFICATION_CODE_ATTEMPT_LIMIT = 5;
const VERIFICATION_CODE_RESENT_BUFFER_TIME_MILLS = 30000;
const VERIFICATION_CODE_EXPIRED_TIME_MILLS = 30000;

const TWELVE_HOURS_IN_MILLS = 43200000;
const ONE_HOUR_IN_MILLS = 3600000;

const ACCESS_TOKEN_TIME_SECONDS = 900; 
const REFRESH_TOKEN_TIME_SECONDS = 259200; 
const TOKEN_ISSUER = 'Unknown2known';
const TOKEN_ALGORITHM = 'RS256';    
const TOKEN_JWT_ID_LENGTH = 16;
const TOKEN_VALIDATED = 'Token verified successfully';
const TOKEN_ROTATED = 'Token rotated successfully';

const DB_CONNECTION_TIMEOUT_MILLIS = 2000;
const DB_MAX_CLIENTS = 20;
const DB_IDLE_TIMEOUT_MILLIS = 30000;

const REDIS_PUBLISH_MESSAGE_MAX_RETRY = 5; 
const REDIS_PUBLISH_MESSAGE_PROFILE_CACHE_KEY = 'create-profile-publish-message-count';
const REDIS_PUBLISH_MESSAGE_MATCH_CACHE_KEY = 'create-match-publish-message-count';

const PAST_DATE_18_YEARS_MILLIS = moment().subtract('18', 'years').unix() * 1000;

export { 
    USER_LOGGED_IN, PAST_DATE_18_YEARS_MILLIS, USER_CREATED, VERIFICATION_CODE_SENT, VERIFICATION_CODE_EMAIL_SUBJECT, TOKEN_VALIDATED,
    VERIFICATION_CODE_EMAIL_TEXT, ACCESS_TOKEN_TIME_SECONDS, REFRESH_TOKEN_TIME_SECONDS, TOKEN_ISSUER, TOKEN_ALGORITHM, 
    TOKEN_JWT_ID_LENGTH, TOKEN_ROTATED, DB_CONNECTION_TIMEOUT_MILLIS, DB_MAX_CLIENTS, DB_IDLE_TIMEOUT_MILLIS, 
    VERIFICATION_CODE_GENERATE_LIMIT, VERIFICATION_CODE_EXPIRED_TIME_MILLS, VERIFICATION_CODE_RESENT_BUFFER_TIME_MILLS,
    TWELVE_HOURS_IN_MILLS, ONE_HOUR_IN_MILLS, VERIFICATION_CODE_ATTEMPT_LIMIT, REDIS_PUBLISH_MESSAGE_PROFILE_CACHE_KEY, 
    REDIS_PUBLISH_MESSAGE_MATCH_CACHE_KEY, REDIS_PUBLISH_MESSAGE_MAX_RETRY
}