import moment from 'moment';

const USER_LOGGED_IN = 'User logged in successfully';
const USER_CREATED = 'User created successfully';

const VERIFICATION_CODE_SENT = 'Verification code sent to your email';
const VERIFICATION_CODE_EMAIL_SUBJECT = 'Verification code';
const VERIFICATION_CODE_EMAIL_TEXT = 'Verification code text';

const ACCESS_TOKEN_TIME_SECONDS = 900; 
const REFRESH_TOKEN_TIME_SECONDS = 259200; 
const TOKEN_ISSUER = 'Unknown2known';
const TOKEN_ALGORITHM = 'RS256';    
const TOKEN_JWT_ID_LENGTH = 16;
const TOKEN_VALIDATED = 'Token verified successfully';
const TOKEN_ROTATED = 'Token rotated successfully';

const DB_CONNECTION_TIMEOUT_MILLIS = 2000;
const DB_MAX_CLIENTS = 20;
const DB_IDLE_TIMEOUT_MILLIS = 30000;

const PAST_DATE_18_YEARS = moment(new Date(Math.floor(new Date().getTime()) - (18*365*24*60*60))).format('DD-MM-YYYY');

export { 
    USER_LOGGED_IN, PAST_DATE_18_YEARS, USER_CREATED, VERIFICATION_CODE_SENT, VERIFICATION_CODE_EMAIL_SUBJECT, TOKEN_VALIDATED,
    VERIFICATION_CODE_EMAIL_TEXT, ACCESS_TOKEN_TIME_SECONDS, REFRESH_TOKEN_TIME_SECONDS, TOKEN_ISSUER, TOKEN_ALGORITHM, TOKEN_JWT_ID_LENGTH,
    TOKEN_ROTATED, DB_CONNECTION_TIMEOUT_MILLIS, DB_MAX_CLIENTS, DB_IDLE_TIMEOUT_MILLIS
}